<?php
$order = $block->getOrder();
?>
<div class="checkout-success">
    <?php if($order->getIncrementId()):?>
        <?php if ($block->getCustomerId()) :?>
            <p><?php echo __('Your order number is: '.$order->getIncrementId().')') ?>
            </p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.',$order->getIncrementId()) ?></p>
        <?php endif;?>
        <p><?php echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>
</div>

<a href="<?php echo $block->getMyUrl($order->getIncrementId())?>">Your order info url </a>